### ISSUE TITLE
Inconsistent effects behavior between the Ocaml and C models 

### ISSUE THREAD

**Issue by abukharmeh** [rems-project/sail#122]
When I try to compile the following code:
```
val      Xd : bits(5)-> bits(64) 
function Xd   index =
  if (sizeof(xlen) == 64)
  then X(index)
  else if (index == 0b00000)
  then X(index)@X(index)
  else X(index+1)@X(index)
```
Sail C model would build and works without any error, but the OCAML model would complain about missing effects {escape, rreg}. I think the C model should also complain about them ? 

SAIL Version: 0.13 obtained from OPAM

**Comment by Alasdair** [comment]
Right now when you enable optimizations when compiling to C the effects are disabled because it does some (benign) rewrites that can remove effects. Nothing in the Sail->C pipeline ever looks at the effect annotations.

I have long been of the opinion that the effects system as it stands should either be scrapped entirely, or changed to better mirror the monadic effects in the Isabelle/HOL4 translations.

**Comment by martinberger** [comment]
> I have long been of the opinion that ... scrapped entirely, or changed  ...

Are there any concrete plans in this direction? The RISC-V spec is full of effect annotations.

**Comment by abukharmeh** [comment]
Following up on this, it appears that the default behavior of the interactive mode is to respect the effects statements and require them !

**Comment by martinberger** [comment]
@abukharmeh The `-just_check` also finds this bug. So maybe just add `-just_check` to your build process?

@Alasdair I agree with you on the effect system. But the optimisations when compiling to C are applied before full type-checking? Can they not be applied afterwards?

**Comment by Alasdair** [comment]
It's to do with the way `undefined : T` is handled when compiling with optimizations I think. This differs depending on the target but for emulators in C and OCaml, the default behavior is to generate (Sail) functions for each type T that create arbitrary values at run time. This is done when desugaring the AST, before type-checking. The `-O` enables several internal options, one of which changes this process so that the generated functions return values chosen at compile time. (This option can be turned on independently with the `-Ofast_undefined` flag).

I think at the time this issue was created the effect annotations had to be exact. This is no longer the case (the annotated effects now only have to be a superset of the actual effects), so it may now be possible to just have `-O` no longer imply `-no_effects`.

**Comment by Alasdair** [comment]
Upon checking it does indeed appear that `-no_effects` is no longer required with `-O`.

**Comment by martinberger** [comment]
Thanks. 

It might be worthwhile updating the manual to clarify that the annotated effects now only have to be a superset of the actual effects. I think that's what people assume anyway.
