### ISSUE TITLE
Does sail support pattern disjunctions?

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#130]
For example:
```
match x {
 0 | 2 => 0,
 1 | 3 => 1
}
```
instead of
```
match x {
 0 => 0,
 2 => 0,
 1 => 1, 
 3 => 1
}
```
The former doesn't parse and it's not mentioned in the manual but I did find 
`P_or` mentioned here https://github.com/rems-project/sail/blob/212b16bd15ea39ae3b35efdce7cef549fe4f1657/src/parse_ast.ml#L216

Obviously a pretty minor thing but I thought maybe I'm just doing it wrong?

**Comment by Alasdair** [comment]
It doesn't. There was a plan to support it at some point, hence there is some support in the code (although not complete).

In the end I don't think it's worth doing because not all our theorem prover targets support pattern disjunctions, and there isn't really a nice way to compile them away without making the generated code really ugly.

**Comment by rmn30** [comment]
OK, just checking. Thanks!
