### ISSUE TITLE
Undefined reference linker error

### ISSUE THREAD

**Issue by abukharmeh** [rems-project/sail#160]
```
val reg_even : forall 'n, 'n > 0. (vector('n, dec, bits(5))) -> bool
function reg_even (registers) = {
  foreach (x from 0 to (length(registers) - 1)) {
    if (registers[x][0] == bitone) then return false
  };
  true
}

```

Hi, While working with SAIL RISC-V model, I tried the function shown above which operates on vector of vectors. SAIL happily compiles it, but it result in a linker error undefined reference to length_zz5vecz8z5bv5z9. Looking at the generated C code, It appears that SAIL compiler generates various functions to deal with the new structure and suffix them _zz5vecrz8z5bv5z9 but missed the length one.

I wonder if this is a bug in the C backend, or something wrong I did ? 

Also I wonder if variable name generation in C backend is deterministic ?

Thanks.

**Comment by Alasdair** [comment]
Another pesky monomorphisation bug! Should be fixed by: https://github.com/rems-project/sail/commit/1ca8798881a4ae8165a17aaf381dcad881c214ea

The variable name generation (and mangling for monomorphised functions) is deterministic, but it isn't guaranteed to be stable. It's inspired by the encoding used by GHC Haskell for creating C-compatible names.
https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/symbol-names

**Comment by abukharmeh** [comment]
Thank you for fixing this quickly. Also thank you for the info about name generation, your commit made it easy to track how the names are generated, I think it uses this snippet:
https://github.com/rems-project/sail/blob/37247bb1767015bfee35d9536040d83cf151339f/src/util.ml#L468-L485
