### ISSUE TITLE
What happened to the c2 backend?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#196]
The changelog for version 0.13 mentions a c2 backend that has a non-global-based API (very good thing) using `sail_state`. In [the sail-riscv Makefile](https://github.com/riscv/sail-riscv/blob/master/Makefile#L242) there's an unused rule that seems to use it:

```
generated_definitions/c2/riscv_model_$(ARCH).c: $(SAIL_SRCS) model/main.sail Makefile
	mkdir -p generated_definitions/c2
	$(SAIL) $(SAIL_FLAGS) -no_warn -memo_z3 -config c_emulator/config.json -c2 $(SAIL_SRCS) -o $(basename $@)
```

And this comment in some Sail code:

```
// FIXME: most of these will no longer be necessary once we use the c2 sail backend.
```

But in the current version (0.15) there's no mention of the c2 backend. There's no `-c2` flag, and `sail_state` exists but is [an empty struct](https://github.com/rems-project/sail/blob/37247bb1767015bfee35d9536040d83cf151339f/lib/sail_state.h#L71) and appears to be unused.

Was the c2 backend abandoned?

**Comment by Alasdair** [comment]
It's sort of abandoned because maintaining two separate backends turned out to be quite a lot of work, and people have become more dependent on the way I initially generated C than I ever intended which makes migrating to anything better hard. I did a big refactoring to modularise the codebase almost a year ago now, and I didn't move that code over.

**Comment by Alasdair** [comment]
A better approach in retrospect would be to incrementally improve the current backend, rather than try to change too many things at once

**Comment by Timmmm** [comment]
Ah good to know, thanks!
