### ISSUE TITLE
Sail does not check index of vector access

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#24]
I was surprised recently to find that sail silently permits access to invalid vector indices e.g.:

[test1.txt](https://github.com/rems-project/sail/files/2595459/test1.txt)

The resulting ocaml executable crashes with `Exiting due to uncaught exception` but the C one appears to exit successfully...

**Comment by arichardson** [comment]
Sounds like we should be running the generated C code under CHERI 😉

**Comment by Alasdair** [comment]
It's because bitvector_access doesn't have a sensible constraint. If you copy the constraint from vector_access it will prevent this.

These bitvector specific functions are hacks for Coq and Isabelle - either we should fix those backends so they understand how to compile generic vectors differently based on their contents (like the C backend does) or we should make it so sail has two types: vector('n, dec, 'a) and bitvector('n, dec). The current solution using an ad-hoc overload will be broken in other cases too.

**Comment by rmn30** [comment]
Yes, I thought it would be the type of the builtin but was wondering if there might be a good reason. Is there  any useful case where it will be too onerous for sail to prove the constraint and if we might need a cheat card?

**Comment by bacam** [comment]
I think this was just an oversight on my part when adding the bitvector version back in.  From the git history it looks like the MIPS and CHERI models already worked with the full constraint, and RISC-V still has its own version with the constraint.  I'll check them now and if it still works commit a version with the constraint.

**Comment by rmn30** [comment]
I already fixed it locally and was just adding a regression test...

**Comment by bacam** [comment]
Should we add similar constraints to the update operations?  The provers will fail in some reasonable way on these, but I'm not so sure about the C and OCaml backends.

**Comment by rmn30** [comment]
Yes, please! Works for CHERI but not sure about other specs.
