### ISSUE TITLE
Typechecker still confused about composed mappings

### ISSUE THREAD

**Issue by nwf-msr** [rems-project/sail#243]
It looks like the fix for #232 (b8d65fdb37c4fed48b350853bb3a67ea4bf68aeb) is incomplete.  A differently minimized example of my model's continued woes (but using the delightful new `struct` patterns in `mapping`s, thanks!):

```
default Order dec
$include <prelude.sail>

enum E = EA | EB

mapping e_pair_bits : (E,E) <-> bits(2) =
  { (EA, EA) <-> 0b00
  , (EA, EB) <-> 0b01
  , (EB, EB) <-> 0b11
  }

struct eful = { e1 : E, v1 : bits(1) }

union F = { FE : eful }

val f_bits : F <-> bits(3)
mapping f_bits = { FE(struct { e1 = e1, v1 = v1 }) <-> e_pair_bits(e1,e1) @ v1 }
```
elicits no errors while checking but, when generating C,
```
Type error:
tmp/test.sail:17.55-78:
17 |mapping f_bits = { FE(struct { e1 = e1, v1 = v1 }) <-> e_pair_bits(e1,e1) @ v1 }
   |                                                       ^---------------------^
   | No overloading for append, tried:
   | * bitvector_concat
   |    No overloading for e_pair_bits, tried:
   |    * e_pair_bits_forwards
   |       Function e_pair_bits_forwards applied to 2 args, expected 1 (1 explicit): (E, E)
   |    * e_pair_bits_backwards
   |       Function e_pair_bits_backwards applied to 2 args, expected 1 (1 explicit): bitvector(2, dec)
```

**Comment by Alasdair** [comment]
I have a fix but need to test it some more because I think the typing rule for nested mappings was just plain incorrect. However, I don't think this should have type-checked at all because of the duplicate variables in `(e1, e1)`, (once this error is fixed it then fails with an error about that, which should be caught earlier).

The following has the same error without the duplicate variable:
```
mapping f_bits = { FE(struct { e1 = e1, v1 = v1 }) <-> e_pair_bits(e1,EB) @ v1 }
```

**Comment by nwf-msr** [comment]
Sorry, while minimizing I didn't think about the importance of variable nonlinearity.  My actual model is linear in its `mapping`s.

**Comment by Alasdair** [comment]
This should be fixed by https://github.com/rems-project/sail/pull/247 which reworks the mapping elaboration - there are probably some exciting new bugs to be found, and some aspects of the other issues still need to be fixed, but I decided to merge that PR for now and address the other issues in a follow-up PR.
