### ISSUE TITLE
Division not supported in type expressions?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#427]
This code:

```
default Order dec

$include <prelude.sail>

type x : Int = 8

type y : Int = x/2

function foo() -> unit = {
  let z = sizeof(y);
}
```

gives:

```
Type error:
test.sail:10.10-19:
10 |  let z = sizeof(y);
   |          ^-------^
   | Cannot re-write sizeof((operator /)(8, 2))
```

It would be really useful to be able to use division in type expressions. For example if you have a size in bits and want to convert it to bytes. Ok in that case you can just do it the other way and use multiplication but there are other uses. E.g. to make a vector that's half the size of another one.

Is this intentional? Perhaps there is difficulty with division by zero or rounding/truncation?

**Comment by Alasdair** [comment]
It is it's just called `div` rather than using the operator. It should really be called `ediv` because it's Euclidian division rather than flooring or truncating division.

The library doesn't pick a single division operator to get the `/` symbol, as each spec may want slightly different semantics. You can do
```
type operator /('n, 'm) = div('n, 'm)
```
but you have to be a little careful as that would usually mean `/` on values has different rounding behaviour to `/` on types, which could be confusing.

**Comment by Alasdair** [comment]
When it comes to Z3 and other SMT solvers constraints of the form `m = X * n` where `X` is a constant are almost guaranteed to work whereas when you start adding other operators you might be relying on rewrites and other heuristics to reduce/simply the problem before the linear arithmetic solver can handle it. For this reason my (conservative) suggestion would be to use multiplication whenever possible, i.e. get bits as `8 * n` bytes rather than getting bytes from `n / 8` bits.

**Comment by Timmmm** [comment]
Aha, this works thanks!

```
default Order dec

$include <prelude.sail>
$include <smt.sail>

type x : Int = 8

type y : Int = div(x, 2)

function foo() -> unit = {
  let z = sizeof(y);
}
```
