### ISSUE TITLE
malformed $ directives are ignored

### ISSUE THREAD

**Issue by Smattr** [rems-project/sail#46]
When you enter a `$` followed by a directive Sail doesn't understand, it seems to get silently ignored. In my case, it was the unfortunate typo:

```sail
$incldue <prelude.sail>
```

I think this is actually a deliberate design to let the Sail preprocessor be agnostic to what directives are supported and let internal modules pick and choose which they want to interpret. It has some awkward side effects for users though. Not sure what can be done about this in the short term, but just wanted to file this in case this behaviour is not actually expected.

**Comment by Alasdair** [comment]
Yep it's partly because they are just passed through until some module decides to use them, although the other reason is I wanted to make sure that it was possible to introduce new directives and add them to code without causing that code to break with the opam release of Sail.

What we can do is add a list of all supported directives and give a warning for unrecognised ones though, I think that would solve this issue.

**Comment by Smattr** [comment]
Wow, speedy response! Thanks, I'll check out the fix!
