### ISSUE TITLE
Line number missing for cannot rewrite error

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#551]
```
val pt_walk :
  forall 'v 'p,
    'v in {32, 39, 48, 57} &
    'p == (if 'v == 32 then 22 else 44).
  (
    int('v)
  ) -> bits('p)

function pt_walk(
  sv_width
) = zeros()
```

gives

```
Type error:
Cannot re-write sizeof('p)
```

Tested on `Sail 0.17.1 (sail2 @ b9f289a180f12cbf26e6972a6e6c63003ffbb66d)`

Also... should it be able to rewrite this? Can't it rewrite it to `if sv_width == 32 then 22 else 44`?

**Comment by Alasdair** [comment]
That's odd, I do get a location:
```
Type error:
test.sail:20.4-11:
20 |) = zeros()
   |    ^-----^
   | Cannot re-write sizeof('p)
```

**Comment by Alasdair** [comment]
If you wrote the type as:
```
val pt_walk : forall 'v, 'v in {32, 39, 48, 57}. int('v) -> bits(if 'v == 32 then 22 else 44)
```
it would be happy, but because in your case it's defined by an equation `'p = if 'v == 32 ...` and we don't try to use equations like that when trying to figure out implicit arguments. The above type without `'p` is probably easier to use as well, because with a explicit `'p` variable the caller needs to figure out how to instantiate it every time the function is called.

**Comment by Timmmm** [comment]
Ah ok that makes sense thanks! In my actual code there's also a `bits('p)` argument which is why I tried to use it in the return type. Oh and I just double checked and it can rewrite it you also have a `bits('p)` argument. That's good.

> That's odd, I do get a location

Very weird. Ah well probably not worth worrying about.

Btw have you noticed that trailing commas in function arguments and types are allowed... unless there is only one argument? I.e. this is fine:

```
function pt_walk(
  sv_width,
  ppns,
) = zeros()
```

This is a syntax error:

```
function pt_walk(
  sv_width,
) = zeros()
```

(Just pointing it out in case it wasn't intentional.)
