### ISSUE TITLE
Could not prove constraints in type synonym

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#556]
This code

```
type level_range('v), 'v in {32, 39, 48, 57} =
  range(0, (if 'v == 32 then 1 else (if 'v == 39 then 2 else (if 'v == 48 then 3 else 4))))

struct PTW_Output('v : Int), 'v in {32, 39, 48, 57} = {
  level   : level_range('v),
}
```

gives this error:

```
Type error:
main.sail:5.12-27:
5 |  level   : level_range('v),
  |            ^-------------^
  | Could not prove constraints 'v in {32, 39, 48, 57} in type synonym range(0, (if 'v == 32 then 1 else (if 'v == 39 then 2 else (if 'v == 48 then 3 else 4)))) with 
```

(There's nothing after the `with`.)

Kind of feels like it should work?

Hope you don't mind me pushing Sail's type system so much! :-D

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/557

> Hope you don't mind me pushing Sail's type system so much! :-D

No, it's very useful actually. There might be other places where type synonyms with constraints don't quite work, every time the code calls `expand_synonyms` it needs to ensure all the constraints have been added to the environment and it's very easy to miss that.

**Comment by Timmmm** [comment]
Ah fantastic, works now!

> No, it's very useful actually. 

Phew :-D
