### ISSUE TITLE
Fatal error with sail coverage

### ISSUE THREAD

**Issue by marnovandermaas** [rems-project/sail#616]
I ran trace with just a single add immediate instruction and the Sail coverage tool exits with the following failure:
```
$ ~/tools/sail/sailcov/sailcov -a all_branches.log -t sail_coverage.log --index 'index' --prefix 'sailcov-html/' riscv-implementations/cheriot-sail/src/*.sail riscv-implementations/cheriot-sail/sail-riscv/model/*.sail 

Warning: assertion failed at File "sailcov/main.ml", line 576, characters 28-35
Warning: assertion failed at File "sailcov/main.ml", line 577, characters 28-35
...
riscv_platform.sail (1/273) 0%
Fatal error: exception Invalid_argument("index out of bounds")
```

Attached are the branch and coverage files. I got this by running on CHERIoT Sail within CHERIoT TestRIG: https://github.com/lowRISC/TestRIG/blob/cheriot/README.md#getting-started
[sail_coverage.log](https://github.com/user-attachments/files/16085295/sail_coverage.log)
[all_branches.log](https://github.com/user-attachments/files/16085327/all_branches.log)

Any idea why this might be happening and how I can fix it?

**Comment by Alasdair** [comment]
This kind of error can happen because the sail binary, sailcov binary, and library that is linked into the emulator all need to match exactly (i.e. be from the same commit on this repository).

If that is not the case then it is likely a bug of some sort. I've had a few similar reports recently but have never had the ability to reproduce the issue and therefore fix it.

**Comment by marnovandermaas** [comment]
Thanks @Alasdair! I rebuilt everything using the latest commit 50299212b8f3989cc56ca0d0005ad4f733723592 and the error went away. I'm going to close this issue.

**Comment by rmn30** [comment]
The warning do still happen, even for the simple test in the test suite. Currently the test suite runner hides them -- I'd suggest adding --werror on the call to `sailcov` in the `run_tests.py`. 

We can't really trust the Sail coverage reports at the moment because of these assertions and because we've seen things like covered regions highlighted within uncovered regions :-(

**Comment by Alasdair** [comment]
I think one issue is sometimes within scattered definitions things can look a bit off because there isn't a separate coverage point for each clause, and the visualizer doesn't know how to highlight every instance simultaneously.

**Comment by rmn30** [comment]
That sounds plausible, thanks. By the way I think the index out of bounds might be caused if the Sail source is edited after generating all_branches and sail_coverage e.g. if line lengths differ?

**Comment by rmn30** [comment]
Yes, I can reproduce it if I remove a line from the `.sail` source after generating taken branches.
