### ISSUE TITLE
Limit compiling targets to this project only:

### ISSUE THREAD

**Issue by dc-mak** [rems-project/sail#69]
I know there's a whole different Makefile-build-system for Coq (as used by BBV) but at least for this Makefile, the following rule can end up rebuilding .vo files in other directories:

https://github.com/rems-project/sail/blob/4525d78142cba80c4f4daaeca79426368f26e77e/lib/coq/Makefile#L17

E.g. Sail2_instr_kinds.v depends on bbv/Word.vo, but instead of using that file, it'll rebuild from Word.v (this can be seen with `make --dry-run`).

Should I change it to
```Makefile
$(TARGET):%.vo: %.v
```
Or is there a more conventional Coq-Makefile-build coming?

**Comment by bacam** [comment]
The build scripts for Coq targets are still pretty rough, partly because I intend to get it to use an opam version of libraries which should remove most of the problems.

In the meantime your change should be fine.  However, I'm surprised it's necessary for you - I find it works OK so long as bbv has been prebuilt and the timestamps are OK (i.e., the `.vo` file is more recent than the `.v`).

**Comment by dc-mak** [comment]
I installed BBV from opam instead of source, so I don't think the timestamps are guaranteed to be in the right order.

**Comment by bacam** [comment]
I added this to the Makefile while sorting out the opam packaging.

**Comment by dc-mak** [comment]
Thanks! And sorry, forgot about this whilst trying to figure out how to use Emacs/Coq from halfway around the world. (Tramp mode is the answer).
