### ISSUE TITLE
Sail -> C without optimizations produces errors on the ARM model

### ISSUE THREAD

**Issue by julienfreche** [rems-project/sail#71]
This is the error I am getting when trying to compile `sail-arm` with the latest sail (sail2 branch)

```
../../sail/sail -c -Oconstant_fold -non_lexical_flow -no_lexp_bounds_check -memo_z3 -no_warn -dno_cast  model/prelude.sail model/no_devices.sail model/aarch_types.sail model/aarch_mem.sail model/aarch64.sail model/aarch64_float.sail model/aarch64_vector.sail model/aarch32.sail model/aarch_decode.sail model/elfmain.sail
Type error:
[model/aarch_mem.sail]:2432:0-2450:1
2432 |function GTESetPPURegion () = {
     |^------------------------------
2450 |}
     |^
     | Effects do not match: {rreg, undef, wreg} declared and {escape, rreg, undef, wreg} found
     | 
```

**Comment by bacam** [comment]
*This* issue should be fixed in the git repo (after the recent release). Could you give that a try?

**Comment by julienfreche** [comment]
Indeed, I updated my sail2 branch and this issue is solved. Many thanks for the quick reply!

**Comment by bauereiss** [comment]
Strangely, our local CI server has been building `sail-arm` for months without this error (presumably the error has been introduced as far back as https://github.com/rems-project/sail/commit/ef81395ecfaaec11f49a62834cf01bc52dd5d91a).  I'm not sure I understand why, maybe it has the `-no_effects` option in an environment variable somewhere.  Since the problem seems to occur with the current opam release of Sail, I guess the proper fix is to release a new Sail version?  A workaround in the meantime could be adding the `-no_effects` option to the `sail-arm` Makefile.
