### ISSUE TITLE
How to use the z3_problem file

### ISSUE THREAD

**Issue by trdthg** [rems-project/sail#785]
Hi, I have never done anything like formal verification or theorem proving, but I want to know how it works and what role does he play in sail-riscv.

So I write a hello world demo with sail, and after sail `hello.sail`, I saw that a z3_problem file was creaed in the directory

![image](https://github.com/user-attachments/assets/d1d1b375-fba0-460d-9682-32d7f055ebd3)

But the format inside looks very strange, I installed z3, tried to run it, and of course it didn't work

Could you please tell me what is the correct way to use it?

**Comment by bacam** [comment]
You don't need to do anything with it - it's a cache file that will make subsequent uses of Sail faster.  It's particularly useful when you're editing (for example) the RISC-V model, because you'll run Sail several times.

Note that by default Sail only type checks its input.  To generate output you need to provide additional options; see the manual for more information.  Alternatively, if you're working with the RISC-V model, there's a `Makefile` that will invoke Sail with the correct options.

**Comment by trdthg** [comment]
Oh, Thank you. I remember that, the `-memo_z3` option
