### ISSUE TITLE
Sail parser in C/C++?

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#89]
I need a Sail lexer + parser in C or C++. Does one exist? If not I'll write (generate) one myself, but want to avoid duplicating effort.

**Comment by PeterSewell** [comment]
Hi Martin,

why do you need that?  It'd be quite some work and hard to get right - more
likely you want to generate something from one of the intermediate
representations...

best,
Peter

**Comment by martinberger** [comment]
Hello Peter, I want to move https://gensim.org/ to a Sail frontend. And
GenSim is written in C++. I'd be delighted to auto-generate the parser from
some intermediate representation. The Sail's Ocaml parser is auto-generated
from OCaml-Yacc, is that so hard to adapt?

Martin

**Comment by martinberger** [comment]
I just had a thought: pretty-printers are the weak inverse of parsers [1, 2], there should be an easy and automatic way of testing new (Sail) parsers. Generate the parsers in a bidirectional	language setting, and then you can test automatically if

     pretty-printer-1 o parser-1
         =
     pretty-printer-2 o parser-2

holds.


[1] Z. Zhu, Y. Zhang, H.-S. Ko, P. Martins, J. Saraiva, Z. Hu, _Parsing and reflective printing, bidirectionally._

[2] Z. Zhu, H.-S. Ko, Y. Zhang, P. Martins, J. Saraiva, Z. Hu, _Unifying Parsing and Reflective Printing for Fully Disambiguated Grammars._

**Comment by martinberger** [comment]
Related to the question of how to validate the parser: how to validate GenSIm against the Sail reference emulators, in a lightweight way that integrates well with the existing CI integration. Probably requires a bit of thinking and infrastructure tweaking.

**Comment by Trolldemorted** [comment]
>It'd be quite some work and hard to get right

We have having the same problem (we want to transpile SAIL into something different). Couldn't one transform your ott specification into something normal parser libraries like flex&bison can handle?

Having ISA specs for all relevant processor architectures is super awesome, but if you can't parse them their usefulness for ancillary research and industry is significantly impared. We could cope with literally any common programming language, but finding personnel that can work with your ocaml stack is borderline impossible :(

**Comment by martinberger** [comment]
@ Benedikt 

I think  an export-to-JSON after type-inference might be good to have.

**Comment by PeterSewell** [comment]
On Wed, 23 Sep 2020 at 16:14, Benedikt Radtke <notifications@github.com>
wrote:

> It'd be quite some work and hard to get right
>
> We have having the same problem (we want to transpile SAIL into something
> different). Couldn't one transform your ott specification into something
> normal parser libraries like flex&bison can handle?
>
> Having ISA specs for all relevant processor architectures is super
> awesome, but if you can't parse them their usefulness for ancillary
> research and industry is significantly impared. We could cope with
> literally any common programming language, but finding personnel that can
> work with your ocaml stack is borderline impossible :(
>
As discussed off-line with Martin, you really don't want to try to re-parse
Sail source and then go from that - just writing the parser might not be
that big a deal, true (though quite irritating to get completely right and
to maintain), but that's only the start; you'd then have to re-create
Sail's type inference engine, and the transformations it does.  There's a
lot of work in there.

Instead, it seems much simpler to work after the Sail front-end has done
its job, where you have a sensible AST, lots of type information, and
various existing transformation passes, some basically Sail-to-Sail, and
some that (eg) translate into the simpler internal language that we use for
C emulation.  It's probably not very hard to generate something that would
be more easily usable for other purposes from that (though whether we have
spare effort to engineer it is unclear).

What do you want to translate it into, and what for?

Peter

**Comment by martinberger** [comment]
> simpler internal language

@PeterSewell Have you got a specific data type in mind that you can point us to?

**Comment by PeterSewell** [comment]
@Alasdair Armstrong
will know better

**Comment by Trolldemorted** [comment]
>As discussed off-line with Martin, you really don't want to try to re-parse
Sail source and then go from that - just writing the parser might not be
that big a deal, true (though quite irritating to get completely right and
to maintain), but that's only the start; you'd then have to re-create
Sail's type inference engine, and the transformations it does.  There's a
lot of work in there.

That is very unfortunate, I already feared that the many language features of SAIL will make this a complicated endeavour, and have been wondering why you added features like type inference to it :( As Alastair Reid has mentioned in his blog post on [ARM's ASL](https://alastairreid.github.io/specification_languages/), specification languages have an even more extreme ratio of writers to readers, so a DSL usually is as simple as possible, with no space for ambiguities, and easy to implement.

Does a clear definition of all that features exist beyond your reference implementation? I suspect the [manual](https://raw.githubusercontent.com/rems-project/sail/sail2/manual.pdf) doesn't explain the type inference in a level of detail that would enable one to understand all its implications or re-implement the lexer/interpreter.

>Instead, it seems much simpler to work after the Sail front-end has done
its job, where you have a sensible AST, lots of type information, and
various existing transformation passes, some basically Sail-to-Sail, and
some that (eg) translate into the simpler internal language that we use for
C emulation.  It's probably not very hard to generate something that would
be more easily usable for other purposes from that (though whether we have
spare effort to engineer it is unclear).

Can you output the post-transformation Sail? Would that be a well-defined reduced subset of Sail, which would have explicit types everywhere and would be easier to parse?


>What do you want to translate it into, and what for?

Into (symbolic) emulators that preserve the call hierarchy (call graph, function names, ...) of the architecture's Sail definition. Your c output doesn't resemble the original functions much (I assume because of heavy unrolling of Sail's syntax sugar), and your isla output has gone through 2 layers of translation and I expect its run-time interpretation to be significantly slower than a direct translation into a native language would be.

Ultimately I want to run os kernels (or kernel components), so the potential input is huge, and someone will always demand faster execution. I originally hoped I could recreate the type inference in languages that inherently have type inference (c#, rust), use dynamic types in languages that have that (python and friends), and mimic the inference with polymorphism in languages that don't (c++, java). While browsing through the arm files I assumed the inference was primarily used to specify bitvectors without manually defining their width, is that correct?

**Comment by martinberger** [comment]
@PeterSewell If Sail gets more popular, and with the choice of Sail for RISC-V and the NVIdia acquision of Arm's this is likely, you will get more and more people wanting to build their tools on top of Sail. So a standardised export option for parsed and type-inferred Sail ASTs would probably save a lot of work for a lot of people.

**Comment by Alasdair** [comment]
> As Alastair Reid has mentioned in his blog post on ARM's ASL, specification languages have an even more extreme ratio of writers to readers, so a DSL usually is as simple as possible, with no space for ambiguities, and easy to implement.

It's worth pointing out that Sail is very similar to ASL in most respects. All the bullet points by Alastair also pretty much apply to Sail (with the exception of the indentation-sensitive point). Some readability features do work against easy to implement however - pattern matching (we think) allows writing more readable code, and having a more flexible type-system allows writing bitvector polymorphic functions rather than having repetition throughout the specification. That said the operational semantics of Sail is very simple.

> I originally hoped I could recreate the type inference in languages that inherently have type inference (c#, rust), use dynamic types in languages that have that (python and friends), and mimic the inference with polymorphism in languages that don't (c++, java). While browsing through the arm files I assumed the inference was primarily used to specify bitvectors without manually defining their width, is that correct?

It is valid to drop all the interesting dependent types and map all bitvectors into a single 'bitvector' type that can represent bitvectors of any length. If you do that you can do an extremely simple translation into a language like OCaml or Haskell where you can let type inference handle everything because they have global type inference. Rust and C# have more limited local forms of type inference, so you'll probably run into limitations with their type inference algorithms.

Internally we do one better than just building a type-annotated abstract syntax tree, we actually attach a full typing context to every node in the AST (using some purely-functional data structures to maximize sharing, so this isn't as inefficient as it sounds). This means that not only can you get the type of every expression in the AST, you can rewrite that expression and then _re-invoke_ the type checker to completely re-annotate all the rewritten sub-expressions at that point. Our simplifying rewrites are then set up so they can use this to preserve the type correctness of the AST, so when you reach any of our backends all the type annotation information is correct w.r.t. the rewritten AST.

This is the main reason why we generally recommend using our OCaml code as a base - I won't deny that there are some ugly bits here and there like any software project that's been going on for a few years, but it's mostly pretty nice to work with.

The rewrites we have mostly do things like simplifying pattern matching away, simplifying assignments, and things like that which are useful for any translation. For our C and SMT backends we have another intermediate language (called Jib, a type of Sail) which is effectively a simple goto-language. For analysis purposes this can also be put into SSA form. It is described by this file:

https://github.com/rems-project/sail/blob/sail2/language/jib.ott

It also greatly simplifies the types, so rather than having dependent types, the translation into that IR will use the typing information to categorise bitvectors into fixed-width, variable-width (with a known upper bound) and variable-width (without a known upper bound). I generally prefer working with this IR whenever possible because it's so much simpler than the full language, although it ends up looking nothing like the original source.

> If Sail gets more popular, and with the choice of Sail for RISC-V and the NVIdia acquision of Arm's this is likely, you will get more and more people wanting to build their tools on top of Sail. So a standardised export option for parsed and type-inferred Sail ASTs would probably save a lot of work for a lot of people.

This is something we should do. It's not hard it just requires time to write it.

**Comment by PeterSewell** [comment]
On Fri, 25 Sep 2020 at 14:50, Alasdair Armstrong <notifications@github.com>
wrote:

> As Alastair Reid has mentioned in his blog post on ARM's ASL,
> specification languages have an even more extreme ratio of writers to
> readers, so a DSL usually is as simple as possible, with no space for
> ambiguities, and easy to implement.
>
> It's worth pointing out that Sail is very similar to ASL in most respects.
> All the bullet points by Alastair also pretty much apply to Sail (with the
> exception of the indentation-sensitive point). Some readability features do
> work against easy to implement however - pattern matching (we think) allows
> writing more readable code, and having a more flexible type-system allows
> writing bitvector polymorphic functions rather than having repetition
> throughout the specification. That said the operational semantics of Sail
> is very simple.
>
> I originally hoped I could recreate the type inference in languages that
> inherently have type inference (c#, rust), use dynamic types in languages
> that have that (python and friends), and mimic the inference with
> polymorphism in languages that don't (c++, java). While browsing through
> the arm files I assumed the inference was primarily used to specify
> bitvectors without manually defining their width, is that correct?
>
> It is valid to drop all the interesting dependent types and map all
> bitvectors into a single 'bitvector' type that can represent bitvectors of
> any length. If you do that you can do an extremely simple translation into
> a language like OCaml or Haskell where you can let type inference handle
> everything because they have global type inference. Rust and C# have more
> limited local forms of type inference, so you'll probably run into
> limitations with their type inference algorithms.
>
> Internally we do one better than just building a type-annotated abstract
> syntax tree, we actually attach a full typing context to every node in the
> AST (using some purely-functional data structures to maximize sharing, so
> this isn't as inefficient as it sounds). This means that not only can you
> get the type of every expression in the AST, you can rewrite that
> expression and then *re-invoke* the type checker to completely
> re-annotate all the rewritten sub-expressions at that point. Our
> simplifying rewrites are then set up so they can use this to preserve the
> type correctness of the AST, so when you reach any of our backends all the
> type annotation information is correct w.r.t. the rewritten AST.
>
> This is the main reason why we generally recommend using our OCaml code as
> a base - I won't deny that there are some ugly bits here and there like any
> software project that's been going on for a few years, but it's mostly
> pretty nice to work with.
>
> The rewrites we have mostly do things like simplifying pattern matching
> away, simplifying assignments, and things like that which are useful for
> any translation. For our C and SMT backends we have another intermediate
> language (called Jib, a type of Sail) which is effectively a simple
> goto-language. For analysis purposes this can also be put into SSA form. It
> is described by this file:
>
> https://github.com/rems-project/sail/blob/sail2/language/jib.ott
>
> It also greatly simplifies the types, so rather than having dependent
> types, the translation into that IR will use the typing information to
> categorise bitvectors into fixed-width, variable-width (with a known upper
> bound) and variable-width (without a known upper bound). I generally prefer
> working with this IR whenever possible because it's so much simpler than
> the full language, although it ends up looking nothing like the original
> source.
>
> If Sail gets more popular, and with the choice of Sail for RISC-V and the
> NVIdia acquision of Arm's this is likely, you will get more and more people
> wanting to build their tools on top of Sail. So a standardised export
> option for parsed and type-inferred Sail ASTs would probably save a lot of
> work for a lot of people.
>
> This is something we should do. It's not hard it just requires time to
> write it.
>
If the type-annotated AST were Ott-defined (I can't remember - maybe it's
not now?), we could auto-generate a naive serialiser.  But the sharing
might mean a smarter thing is necessary in any case.

**Comment by martinberger** [comment]
> This is the main reason why we generally recommend using our OCaml code as a base

Without wishing to start a language war ;-) Ocaml is rather niche from the POV of processor designers. They won't rewrite their Gem5, JasperGold, Spike, OWHY, in Ocaml, in order to use Sail. I recommend assuming that most future use cases of Sail's will feed it into C++.

**Comment by Alasdair** [comment]
I'm not suggesting they should write everything in OCaml, just using the OCaml infrastructure to generate whatever is required to then feed into C++. For example, my [symbolic execution tool](https://github.com/rems-project/isla) is written in Rust for many of the same reasons someone might want to use C++, but I have a little 328 line OCaml program [here](https://github.com/rems-project/isla/blob/master/isla-sail/main.ml) that uses the OCaml library provided by Sail to transform the specification into the form my Rust code consumes.

We're going to take a look at some of the json libraries in OCaml to see if any of them can generate a useful serialization without much effort.

**Comment by martinberger** [comment]
@Alasdair 328 lines of OCaml is very nice. But I recommend to contemplate  0 lines of Ocaml for exporting to C++,  or some standard format, at least as a long term goal. The good thing is that the Sail -> <other language> isn't performance critical, so something very simple should be OK.

**Comment by martinberger** [comment]
An alternative to JSON might be Protobuf, Google's cross-language mechanism for serialising data-structures.

**Comment by PeterSewell** [comment]
On Fri, 25 Sep 2020 at 18:17, Martin Berger <notifications@github.com>
wrote:

> An alternative to JSON might be Protobuf, Google's cross-language
> mechanism for serialising data-structures.
>
We should probably use whichever of the common formats there exists
standard easy OCaml tooling to generate the serialisation code for.

**Comment by martinberger** [comment]
That's likely JSON, I think that Ocamlbuild has a preprocessor mode that
let's you auto-derive JSON declarations from Ocaml types.

**Comment by martinberger** [comment]
> https://github.com/rems-project/sail/blob/sail2/language/jib.ott

Side question, the lowering from full Sail to this IR, is it just sound or fully abstract? I know this is a difficult question to answer and depends on a variety of things, but maybe you have had some thoughts about it already.

**Comment by Alasdair** [comment]
It should be sound, but it isn't fully abstract.

The reason is there are multiple bitvector types in the IR for performance reasons, and you can construct examples of equivalent programs in the source one of which will use a faster representation and the other will not. It might be fully abstract if you were to always map into the least efficient representation (at the cost of a huge performance hit) but I haven't really thought about this.

**Comment by martinberger** [comment]
Presumably there is a coherent story on what context can see the lack of
full-abstraction, and then, by fiat, rule them out.

**Comment by PeterSewell** [comment]
It's basically a whole-program transformation in any case - not sure one
should care too much about sticking a part of the generated C in some other
context.

**Comment by Alasdair** [comment]
In my above example the problem is you can create two functions that are equivalent in Sail but because they can end up with different types in the IR, it's not clear that they even fit in the same context. To start thinking about full-abstraction I think we'd have to start by thinking about what a 'component' is in some sense. I hope this makes sense, as I'm not fully familiar with the literature on fully abstract compilation.

**Comment by martinberger** [comment]
Full abstraction is really tricky in most cases. For our pragmatic purposes
in fast emulators, I imagine that those failures of full abstraction can be
ignored, at least for the time being, or else we never get a Sail frontend
for GenSim. There could be interesting research questions though.

**Comment by Trolldemorted** [comment]
I have seen that the [minisail executable](https://github.com/rems-project/minisail/blob/45781fc3ba75a3e08452dbbd07a49ffd29c82b05/src/main.ml#L12) has a `-dump_raw_ast` option, does it solve this problem? Is the dumped AST's structure defined somewhere beyond the source code?

**Comment by leonardopsantos** [comment]
Reviving this thread.

> We have having the same problem (we want to transpile SAIL into something different). 

We do too. OCaml is a barrier for adoption for my company. Like other said before, regardless of the merits of OCaml as a language, it's a niche language. I simply won't be given company time to learn OCaml to the level where I could write a C++ or Python backend, for example.

My company has developed an ASIC with RISC-V core with custom extensions. We didn't use SAIL, but I'm pushing for us to move everything into SAIL. Having a SAIL parser in a more popular language would go a long way in presenting the case that adopting SAIL is a worthwhile effort.

**Comment by Alasdair** [comment]
I think in practice just a parser by itself is not that useful. Once you have parsed the source, you will invariably want to perform operations on it like the various lowering-passes, type-system checks, translations into intermediate representations, and so on.

For example, if you wanted to transpile Sail into Python, it believe would take significantly less time for an experienced engineer to learn OCaml and then implement it using our existing infrastructure, than to duplicate what might end up being multiple man-years worth of engineering effort re-implementing a lot of existing compiler infrastructure in another language.

Note that I'm not intrinsically opposed to making Sail more consumable from other languages, but I wonder if time would be better spent carving out a stable-ish C API for the existing compiler infrastructure that could be called from any language. I do understand why companies don't want to invest time in new languages, but for the same reason it's also very hard for us to justify anything that amounts to doing what we've done before but in a different language.

**Comment by martinberger** [comment]
> Having a SAIL parser in a more popular language would go a long way in presenting the case that adopting SAIL is a worthwhile effort.

Maybe https://github.com/pydrofoil/pydrofoil is of interest?

**Comment by PeterSewell** [comment]
On Fri, 5 Apr 2024 at 21:23, Martin Berger ***@***.***> wrote:

> Having a SAIL parser in a more popular language would go a long way in
> presenting the case that adopting SAIL is a worthwhile effort.
>
>
It's a mistake to think of this kind of thing as a "parser" - to be useful,
it would have to accurately capture the Sail dynamic semantics, and to some
extent also the type system.

If test generation is the main goal, then one should look at @Brian Campbell
***@***.***> 's work on generating tests from Sail
specifications that give good test coverage, eg as described in our Morello
paper.


> Maybe https://github.com/pydrofoil/pydrofoil is of interest?
>
IIRC that takes one of the Sail intermediate languages as input - those are
much simpler than the source language. For fast emulation; that's good.
Whether it would be a good source for property-based testing, I don't know.

Peter

**Comment by martinberger** [comment]
> *IIRC that takes one of the Sail intermediate languages as input - those are much simpler than the source language. For fast emulation; that's good. Whether it would be a good source for property-based testing, I don't know. Peter*

Yes, Pydrofoil takes JIB as input. 

Python has mature property-based testing frameworks, and I think orchestrating PBT from a widely known language like Python is likely be help beginners. Can you give examples of PBT that you think requires source Sail and cannot be done with JIB?

**Comment by martinberger** [comment]
@leonardopsantos https://github.com/avisi-group/borealis has a Sail -> Rust parser. Not sure how mature it is at this point.
