### ISSUE TITLE
Possible parallelism of some phases?

### ISSUE THREAD

**Issue by talsewell** [rems-project/sail#90]
I am idly waiting as a process that makes use of sail type checks a large sail specification.
CPU utilisation is not high, sometimes as low as 30%. I take it some things are somehow
waiting on IO.

I'm considering importing parmap and making some of the maps across definitions run in
parallel, e.g. "Adding casts" in src/monomorphise.ml.

Is this a good idea? Are things generally thread safe or will it all end in tears?

**Comment by Alasdair** [comment]
OCaml doesn't support multi-threading, so the parmap library is really forking multiple processes and then marshalling the result back to the parent process via some mmap hackery to make it look like shared memory. This means that some thread-safety issues won't apply, as all the internal data structures will be copied. Within Sail this means that the cache for memoizing SMT queries will be copied, so each process might duplicate SMT queries made by other processes (which could cause an overall slowdown). It also means all cached SMT queries made during the parmap will be thrown away after the parmap joins, whereas normally with the -memo_z3 flag they will be preserved between runs.

Other than that SMT caching infrastructure everything that is done on a per-function basis should be pretty much stateless so I can't imagine any problems.

**Comment by bacam** [comment]
I'm a bit suspicious of that 30% CPU utilisation.  I'd be surprised if it's storage I/O, but it probably has poor memory locality due to repeatedly passing over the AST (I wonder if fusing together multiple rewrites might help), but I think the real cause might be waiting on short-lived Z3 processes.

Elsewhere we're probably doing some really dumb things whose performance could be improved without going parallel.  For example, I wouldn't be surprised if we make far too many queries to the solver to find unique solutions of type-level constants.  I think Thomas B mentioned that that's a problem with the cast insertion.  I've a dim memory that it may defeat caching when starting from scratch because it frequently encounters the same problem but with some extra irrelevant hypotheses.

**Comment by talsewell** [comment]
Hmm, yuck. I hadn't realised that parmap was doing marshalling.

Also, after looking again, it appears that when all the solver results necessary are in the cache,
the CPU utilisation improves. The type checking is still slow, but that's not an issue with a simple
fix. I'm happy to mark this issue us not worth further investigation.
